version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bookhive-app:latest
    container_name: bookhive-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - bookhive-network

  webserver:
    image: nginx:alpine
    container_name: bookhive-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bookhive-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: bookhive-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bookshare
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - bookhive-network

volumes:
  dbdata:

networks:
  bookhive-network:
    driver: bridge