<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Category: {{ $category->nom }}</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            font-size: 12px;
            line-height: 1.4;
            margin: 20px;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .info { 
            margin-bottom: 20px; 
        }
        .books { 
            margin-top: 30px; 
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 10px;
        }
        th, td { 
            border: 1px solid #ddd; 
            padding: 8px; 
            text-align: left; 
        }
        th { 
            background-color: #f2f2f2; 
            font-weight: bold;
        }
        .section-title {
            background-color: #d63384;
            color: white;
            padding: 8px;
            margin: 20px 0 10px 0;
            border-radius: 4px;
            font-weight: bold;
        }
        .badge {
            background-color: #17a2b8;
            color: white;
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 10px;
            display: inline-block;
        }
        .info-table {
            width: 100%;
            border: none;
        }
        .info-table td {
            border: none;
            padding: 5px 0;
        }
        .info-table td:first-child {
            width: 30%;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 style="margin: 0; color: #d63384;">Category Details</h1>
        <p style="margin: 5px 0;">Generated on: {{ now()->format('M d, Y \a\t H:i') }}</p>
    </div>
    
    <div class="info">
        <div class="section-title">Category Information</div>
        <table class="info-table">
            <tr>
                <td>Name:</td>
                <td>{{ $category->nom }}</td>
            </tr>
            <tr>
                <td>Description:</td>
                <td>{{ $category->description ?? 'No description provided' }}</td>
            </tr>
            <tr>
                <td>Number of Books:</td>
                <td><span class="badge">{{ $category->books_count }}</span></td>
            </tr>
            <tr>
                <td>Created Date:</td>
                <td>{{ $category->created_at->format('M d, Y') }}</td>
            </tr>
            <tr>
                <td>Last Updated:</td>
                <td>{{ $category->updated_at->format('M d, Y') }}</td>
            </tr>
        </table>
    </div>
    
    @if($category->books_count > 0)
    <div class="books">
        <div class="section-title">Books in this Category ({{ $category->books_count }})</div>
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th>Type</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($category->books as $book)
                <tr>
                    <td>{{ $book->titre }}</td>
                    <td>{{ $book->auteur }}</td>
                    <td>{{ $book->type ?? 'N/A' }}</td>
                    <td>
                        @if($book->is_valid)
                            <span style="color: green;">● Valid</span>
                        @else
                            <span style="color: orange;">● Pending</span>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @else
    <div class="books">
        <div class="section-title">Books in this Category</div>
        <p style="text-align: center; color: #666; font-style: italic;">
            No books found in this category.
        </p>
    </div>
    @endif

    <div style="margin-top: 40px; text-align: center; color: #666; font-size: 10px;">
        <p>Generated by Library Management System</p>
    </div>
</body>
</html>